### ISSUE TITLE
Machine Learning Thermo Class

### ISSUE THREAD

**Issue by bissantz** [AndreWeiner/mlfoam#3]
Hi André,

Holger has introduced the OpenFoam Committee's in a meeting today and has pointed me to this repository.
As you might remember, I am doing research on chemically reactive flows. This involved writing a new thermo class that includes an runtime selectable machine learning backend (currently libtorch) which provides my simulation with thermophysical properties such as density, thermal conductivity etc. 
Holger has pointed out that this piece of code might be interesting for a discussion for your TC and might be a good starting point for further development.

Is there already a repository available where I could share the code?

Best regards,
Julian

**Comment by AndreWeiner** [comment]
Hi Julian,
first of all, I think it's awesome that you want to share your work! Do you already host your project somewhere? We would like to use this repository to aggregate links to projects rather than trying to collect all the source code. I think organizing a bunch of different projects that are all under development and have many different dependencies and developers in one single repository is doomed to end in chaos :-)
I wrote up some initial [contribution guideline](https://github.com/AndreWeiner/mlfoam/blob/main/CONTRIBUTING.md). If your project is already hosted somewhere, I'll add it to the list of research projects.
Best, Andre

**Comment by hmarschall** [comment]
Hi Julian, Hi @AndreWeiner,
I would be interested in having a code discussion, since I am working on a multi-component transport library which is capable to hold individual thermoPhysicalProperties specific to each distinct species mixture. Maybe you, @AndreWeiner, can join as well?
Best regards,
Holger

**Comment by bissantz** [comment]
Hi André, hi Holger,

I apologize for the late reply, I was occupied with a paper deadline in the last month.

@hmarschall I would welcome a code review and can offer an appointment this month. 
@AndreWeiner would you be interested in joining the discussion?

Best,
Julian

**Comment by AndreWeiner** [comment]
Hi Julian,
sure, I would be interested, and I guess @tmaric would be interested as well. Could you create a Doodle with dates/times to your convenience and pass it around? You find my mail [here](https://www.tu-braunschweig.de/ism/forschung/modellierung-und-regelung-von-stroemungen/mitarbeiter/weiner) and those of Tomislav and Holger [here](https://www.mma.tu-darmstadt.de/index/mitarbeiter_3/index.en.jsp) just in case you need them.
Thanks!
Andre
